export const INGREDIENTS = {
    UPDATE_INGREDIENTS: "UPDATE_INGREDIENTS",
    GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST",
    GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS",
    GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR"
};

export const TOTAL_PRICE = {
    ADD: "TOTAL_PRICE.ADD",
    REMOVE: "TOTAL_PRICE.REMOVE",
    RESET: "TOTAL_PRICE.RESET"
};

export const ORDERS = {
    PURCHASE_REQUEST: "PURCHASE_REQUEST",
    PURCHASE_SUCCESS: "PURCHASE_SUCCESS",
    PURCHASE_FAIL: "PURCHASE_FAIL",
    FETCH_ORDERS_START: "FETCH_ORDERS_START",
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAIL: "FETCH_ORDERS_FAIL"
};

export const PURCHASE_INIT = "PURCHASE_INIT";

export const AUTH = {
    START: "AUTH_START",
    SUCCESS: "AUTH_SUCCESS",
    FAIL: "AUTH_FAIL",
    LOGOUT: "AUTH_LOGOUT",
    SET_AUTH_REDIRECT_PATH: "SET_AUTH_REDIRECT_PATH"
};
